services:
  backend:
    build:
      context: ./my-ci-cd-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    container_name: ci-cd-backend
    networks:
      - ci-cd-network

  frontend:
    build:
      context: ./my-ci-cd-fontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    container_name: ci-cd-frontend
    depends_on:
      - backend
    networks:
      - ci-cd-network
    environment:
      - VITE_API_URL=http://backend:8080

networks:
  ci-cd-network:
    driver: bridge
