name: Backend CI/CD

on:
  push:
    branches: ["demo"]
    paths:
      - "my-ci-cd-backend/**" # รันเฉพาะเมื่อมีการแก้ฝั่ง Backend

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Build with Maven
        run: |
          cd my-ci-cd-backend
          chmod +x mvnw
          ./mvnw clean test # รัน Build และ Unit Test พร้อมกัน
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        if: ${{ secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != '' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./my-ci-cd-backend
          push: ${{ secrets.DOCKER_USERNAME != '' && secrets.DOCKER_PASSWORD != '' }}
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/ci-cd-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/ci-cd-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
