name: Frontend CI/CD

on:
  push:
    branches: ["demo"]
    paths:
      - "my-ci-cd-fontend/**" # ตรวจสอบชื่อโฟลเดอร์ "fontend" ให้ตรงกับใน Git

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install and Test
        run: |
          cd my-ci-cd-fontend
          pnpm install --no-frozen-lockfile
          pnpm run test:unit # รัน Vitest เพื่อตรวจสอบความถูกต้อง

  deploy:
    needs: test-frontend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/demo' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./my-ci-cd-fontend
          file: ./my-ci-cd-fontend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/my-ci-cd-frontend:latest
            ${{ secrets.DOCKER_USERNAME }}/my-ci-cd-frontend:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/my-ci-cd-frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/my-ci-cd-frontend:buildcache,mode=max
  